name: conform
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - python=3.7
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - tensorflow==2.4.0
    - torch==1.7.1
    - mlagents==0.22.0
    - mlagents-envs==0.22.0
    - ray[all]==1.1

