name: conform
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - python=3.7
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - -e ../../src/

